### ISSUE TITLE
Error when running apk_verification

### ISSUE THREAD

**Issue by FafnerKeyZee** [certsocietegenerale/fame_modules#2]
Hello,

Got the follwoing error while running apk_verification:

2017-03-23 18:08: error: apk_verification: Could not run on /home/USER/fame/storage/SAMPLEHASH/APKNAME.apk.
 Traceback (most recent call last):
  File "/home/USER/fame/fame/core/module.py", line 471, in _try_each
    return self.each_with_type(target, file_type)
  File "/home/USER/fame/fame/core/module.py", line 430, in each_with_type
    return self.each(target)
  File "/home/USER/fame/fame/modules/community/processing/apk_verification/apk_verification.py", line 95, in each
    ref_apk = self.download_reference_apk()
  File "/home/USER/fame/fame/modules/community/processing/apk_verification/apk_verification.py", line 81, in download_reference_apk
    data = api.download(self.results['package'], version, offer_type)
  File "/home/USER/fame/env/local/lib/python2.7/site-packages/googleplay_api/googleplay.py", line 315, in download
    cookie = message.payload.buyResponse.purchaseStatusResponse.appDeliveryData.downloadAuthCookie[0]
IndexError: list index out of range

Best regards,

**Comment by gaelmuller** [comment]
I don't seem to be able to reproduce this. Can you share a failing APK / Hash ? Is it failing for all APKs ?

**Comment by gaelmuller** [comment]
I found a way to reproduce by using an APK with a package name that is not if the Google Play Store. Cloud you confirm if this is your case ?

**Comment by FafnerKeyZee** [comment]
It's failling for one apk, I will share your the file asap. I didn't test for others ./

But yes it enters in the case you spotted

Best regards,

**Comment by gaelmuller** [comment]
Ok in that case no need to share the APK. apk_verification is only useful if there is a matching APK in the Play Store.

I'm keeping this issue open for now because we need to better handle this case.
