### ISSUE TITLE
[Cuckoo module] Seems cuckoo 2.0 has no module working with.

### ISSUE THREAD

**Issue by deft01** [certsocietegenerale/fame_modules#29]
Hi,

I'm trying to use the **Cuckoo module** working with my **Cuckoo 2.0 instance**.

### **I have some questions :**
- Is the plugin out of date and not compatible with cuckoo?
In this case did someone forked it for Cuckoo 2.* ? As I can see some people added the request years ago : https://github.com/certsocietegenerale/fame_modules/issues/7.
Can you mention in the WebUI and the repo this module is only for Cuckoo 1.0 if it's the case ? This would have saved me a lot of time debugging.

- Am I doing something wrong ? Am I missing something ?

### **My versions :**
cuckoo : 2.0.7
fame : latest

### **1. I started debugging the actual Cuckoo module.**
1.1. I noticed first the Bearer Token from the Cuckoo API wasnt supported. So I hardcoded mine in the header request. This way I got a Cuckoo server authent & answer.

1.2. Then I found out the server answer seems not being handled correctly. As you can see : 

```2020-01-17 16:47: debug: Trying to queue module 'apk'
2020-01-17 16:47: debug: Trying to queue module 'bamfdetect'
2020-01-17 16:47: debug: Trying to queue module 'cuckoo'
2020-01-17 16:47: debug: Trying to queue module 'eml'
2020-01-17 16:47: debug: Trying to queue module 'exiftool'
2020-01-17 16:47: debug: Trying to queue module 'zip'
2020-01-17 16:47: debug: Trying to run cuckoo
2020-01-17 16:47: debug: Trying to run exiftool
2020-01-17 16:47: error: cuckoo: Could not run on /opt/fame/storage/955faa2fcec977b29fb7dc49a80b8c7916c410b70ad973c7883ed8537126f81f/Diskmon.exe.
 Traceback (most recent call last):
  File "/opt/fame/fame/core/module.py", line 492, in _try_each
    return self.each_with_type(target, file_type)
  File "/opt/fame/fame/modules/community/processing/cuckoo/cuckoo.py", line 91, in each_with_type
    options = self.define_options()
  File "/opt/fame/fame/modules/community/processing/cuckoo/cuckoo.py", line 127, in submit_file
KeyError: 'task_id'

2020-01-17 16:47: debug: Done with cuckoo
2020-01-17 16:47: debug: Done with exiftool
```

**Comment by gaelmuller** [comment]
Hello, sorry about the delay. Are you still having this issue ?

We actually have a similar issue opened here: https://github.com/certsocietegenerale/fame/issues/73

I would have to investigate because the `cuckoo` module is designed to work with Cuckoo 2 and actually does in my setup. Could you please share your module's configuration ?

**Comment by deft01** [comment]
Hi,
I don't have this issue anymore because i patched the module. I will make the pull request very soon (next week).

**Comment by deft01** [comment]
I have done the pull request here : https://github.com/certsocietegenerale/fame_modules/pull/34.

**Comment by gaelmuller** [comment]
I'm closing this issue since the module seems to be working properly with Cuckoo 2. Do not hesitate to reopen if needed.
