### ISSUE TITLE
No such file or directory?

### ISSUE THREAD

**Issue by xme** [certsocietegenerale/fame_modules#5]
I'm building a Docker image of FAME, I really enjoy the tool.
I'm facing this problem when I submit some samples:

2017-04-01 16:59: error: cuckoo_modified: Could not run on /opt/fame/storage/dba93180379cbc5dceb62a89af92041274241d8dae97572abf4946a5030067d8/wvpdl.pif.
 Traceback (most recent call last):
  File "/opt/fame/fame/core/module.py", line 471, in _try_each
    return self.each_with_type(target, file_type)
  File "/opt/fame/fame/modules/community/processing/cuckoo_modified/cuckoo.py", line 100, in each_with_type
    self.submit_file(target, options)
  File "/opt/fame/fame/modules/community/processing/cuckoo_modified/cuckoo.py", line 136, in submit_file
    fp = open(filepath, 'rb')
IOError: [Errno 2] No such file or directory: u'/opt/fame/storage/dba93180379cbc5dceb62a89af92041274241d8dae97572abf4946a5030067d8/wvpdl.pif'

The file is present (& readable) in the directory. Any idea?

/x

**Comment by gaelmuller** [comment]
Are you still having this issue ? Is it only when using inside a docker ?

This might be a configuration error if you have remote workers (workers that are not on the same system as the web server). A worker with the setting ```remote=False``` will try to load the files from the filesystem and they will only be present on a local worker.

**Comment by gaelmuller** [comment]
Closing this. Do not hesitate to reopen if needed.
