### ISSUE TITLE
each_with_type with JS uploads

### ISSUE THREAD

**Issue by joesecurity** [certsocietegenerale/fame_modules#6]
`2017-04-05 10:13: debug: Trying to queue module 'bamfdetect'
2017-04-05 10:13: debug: Trying to queue module 'joe'
2017-04-05 10:13: debug: Trying to run joe
2017-04-05 10:22: error: joe: Could not run on /home/jbxtest/fame/storage/a1118b689effce96240a82d701c2aa8c2e718512c29edff30412cfa5e8b69c83/Delivery-Details.js.
 Traceback (most recent call last):
  File "/home/jbxtest/fame/fame/core/module.py", line 471, in _try_each
    return self.each_with_type(target, file_type)
  File "/home/jbxtest/fame/fame/modules/community/processing/joe/joe.py", line 105, in each_with_type
    self.process_report()
  File "/home/jbxtest/fame/fame/modules/community/processing/joe/joe.py", line 192, in process_report
    self.extract_iocs(response)
  File "/home/jbxtest/fame/fame/modules/community/processing/joe/joe.py", line 247, in extract_iocs
    for prefix, event, value in parser:
  File "/home/jbxtest/fame/env/local/lib/python2.7/site-packages/ijson/common.py", line 65, in parse
    for event, value in basic_events:
  File "/home/jbxtest/fame/env/local/lib/python2.7/site-packages/ijson/backends/python.py", line 185, in basic_parse`

**Comment by udgover** [comment]
After discussion with @joesecurity, the issue finally came from an old version of OpenSSL.
