### ISSUE TITLE
Error with the `extract` module when filenames have non-ascii characters

### ISSUE THREAD

**Issue by Augustin-FL** [certsocietegenerale/fame_modules#75]
When trying to extract a .zip containing filenames with non-ascii characters, the extract module returns an error:

```
Traceback (most recent call last):
  File "/extract.py", line 31, in <module>
    with libarchive.public.file_reader(target, passphrases=password_candidates) as ar:
  File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/libarchive/adapters/archive_read.py", line 295, in _enumerator
    opener(archive_res)
  File "/usr/local/lib/python3.7/site-packages/libarchive/adapters/archive_read.py", line 318, in opener
    _archive_read_open_filename(archive_res, filepath, block_size)
  File "/usr/local/lib/python3.7/site-packages/libarchive/adapters/archive_read.py", line 74, in _archive_read_open_filename
    filepath = filepath.encode(_ASCII_ENCODING)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 35: ordinal not in range(128)
```

The error seems to be caused by https://github.com/dsoprea/PyEasyArchive/issues/52

**Comment by Augustin-FL** [comment]
Fixed by 79d1211
